### ISSUE TITLE
If you changed project repository to this one, please

### ISSUE THREAD

**Issue by lzblack** [allegramcd/allegrassilks.me#1]
1. link the domain you purchased to this repository,
2. inform me on Canvas (or Slack/email).
3. add repository description and website domain (How to: stackoverflow.com/questions/7757751/how-do-you-change-a-repository-description-on-github/64942409#64942409)

**Comment by allegramcd** [comment]
I'm not really sure how it's linked i know the website link works, maybe we can go over it in office hours i'm a little confused.
